### ISSUE TITLE
Computational performance issues with large amounts of molecular data

### ISSUE THREAD

**Issue by kikikikikinanana** [RekerLab/DeepDelta#1]
Hi, first of all, thank you for your project repository and research achievements.
I tried to train a dataset of 3800 compounds for smiles-molecule-property pairs with DeepDelta architecture on a desktop environment with 5950x (16c 32t), 3080ti 12G, 128GB RAM. 
When I monitor the resources, it looks like it is using the GPU for training (I can see the python process in nvidia-smi), but the utilization is extremely low (around 10%) and the vram utilization is also low, around 600MB. CPU utilization shows a single core at 100% full load and RAM usage is also high. The 1 epoch training speed is measured at 20it/s, and it takes about 3 hours to train 1 epoch. With the default settings, it takes 5 epochs * 10 folds = 150 hours. I applied the num workers 32 and cache cutoff inf arguments, but it didn't change. I would like to know if this is actually a normal estimated time on my desktop environment or if it is an abnormally slow situation.
I would also like to know the computing power and configuration you used to train the deepdelta model, and the time spent training. Thanks!

**Comment by zacharyfralish** [comment]
Thank you very much for your interest in the project. Apologies for the delayed response, I missed this message initially. For our work with DeepDelta, we ran all code using CUDA 11.4 on GPUs with at least 60GB of memory through the Duke Compute Cluster. Our runs with our datasets were notably faster, however, this was because the largest dataset we ran with this architecture was a total 1321 datapoints. Due to the combinatorial nature of the paired approach of DeepDelta, it has greatly increased computational costs with increased training data set sizes. As such, we believe this and similar paired methods are optimally suited for smaller datasets (< 1500 datapoints) and provide the benefit of allowing these smaller datasets to be appropriately applied to data-hungry deep learning models. Ultimately, given how large your initial dataset is (3800 compounds), I believe that time is not abnormally slow.
